### ISSUE TITLE
Spostare punti

### ISSUE THREAD

**Issue by pcav** [pcav/pirati#1]
Porto Farina (in Tunisia, non vicino a Napoli) 
https://www.openstreetmap.org/node/470285468 

    Cap Roux (molto più in giù tra Cannes e Saint Raphael)
https://www.openstreetmap.org/node/5551164267#map=13/43.4317/6.8867

    Roquebrune (è Cap Martin, praticamente Mentone)
https://www.openstreetmap.org/relation/174558

    Herradura (tra Almeria e Malaga)
https://www.openstreetmap.org/node/888968727

    Al Mahdiyah (è in Tunisia non in Egitto)
https://www.openstreetmap.org/relation/7152281

    Karatas Burun (Turchia)
https://www.openstreetmap.org/relation/1727292#map=10/36.5863/30.4871

    Sicione (dall'altra parte del golfo di Corinto)
https://www.openstreetmap.org/node/1767693612#map=10/37.9567/22.8735

**Comment by pcav** [comment]
Sistemati tutti, eccetto Al Mahdiyah, in quanto nella tabella sono presenti 5 records con questo nome, ma con regione Egitto (gli altri sono effettivamente in Tunisia).
Vanno spostati tutti, oppure solo quelli segnati com Regione=Tunisia?

**Comment by Federico81** [comment]
Al Mahdiyah è tutte le volte quella in Tunisia (sul mare, una specie di
istmo si vede)

Il giorno gio 26 ott 2023 alle ore 09:24 Paolo Cavallini <
***@***.***> ha scritto:

**Comment by pcav** [comment]
OK, quindi correggo aanche la regone, corretto?
Graazie.

**Comment by Federico81** [comment]
esatto :)

Il giorno gio 26 ott 2023 alle ore 14:22 Paolo Cavallini <
***@***.***> ha scritto:

**Comment by pcav** [comment]
Fatto. Per cortesia verifica che non ce ne siano altri, e se appropriato chiudi il ticket.
Grazie.
