### ISSUE TITLE
Definire filtri

### ISSUE THREAD

**Issue by pcav** [pcav/pirati#10]
aggiunto un filtro sulla base delle affiliazioni.
Da decidere quali altri siano interessanti (ad es. uno slider per gli anni, ecc.)

**Comment by Federico81** [comment]
Non saprei qua l'unico altro filtro che mi viene in mente è la provenienza "da dove" ma non mi pare che abbiamo un dato tanto utile nel database... gli anni non saprei, al massimo per fasce (prima della caduta di Rodi, fino alla battaglia di Prevenza, l'assedio di Malta e fino alla fine) ma secondo me non ha tanto senso neanche questo

**Comment by pcav** [comment]
ovviamente la decisione è tua. per ora ho configurato un filtro sulla base dell´affiliazione (`per`). dal mio punto di vista è molto interessante, ma appunto lascio a te l´ultima parole, posso rimuoverlo. per la divisione in periodi possiamo aggiungere la colonna, oppure aggiungere uno slider. se vuoi lo configuro così vedi se ha senso.
graziie.

**Comment by Federico81** [comment]
Secondo me così com'è va bene, è l'unico filtro utile.
- da_dove necessiterebbe un lavoro sul database che ora non riesco a fare e non ha nemmeno tanto senso, era un mondo meticcio, un sacco di italiani combattevano per i turchi
- le fasce degli anni secondo me nemmeno, si ci sono state battaglie più importanti di altre (Rodi 1522, Preveza 1538, Djerba 1560m Malta 1565, Lepanto 1571) ma sono eventi, hanno segnato fasi del conflitto ma non vedo l'utilità di fare una divisione di questo tipo (magari c'è eh, però forse preferisco avere sempre lo sguardo d'insieme) anche perché forse si rischia di fare una cosa da super esperti del sedicesimo secolo

**Comment by pcav** [comment]
benissimo, allora lascio  a te a decisione se chiudere il ticket

**Comment by Federico81** [comment]
chiuso

Il giorno ven 17 nov 2023 alle ore 10:58 Paolo Cavallini <
***@***.***> ha scritto:
