### ISSUE TITLE
Aggiungere riceerca

### ISSUE THREAD

**Issue by pcav** [pcav/pirati#11]
è ossibile aggiungere una ricerca. per cortesia fammi sapere su quali campi (fino a tre).
grazie.

**Comment by Federico81** [comment]
- per chi combatte sicuro
le altre non saprei (anno? fascia di anni?), regione già mi pare non abbia senso

**Comment by pcav** [comment]
per chi è già presente nel filtro, mi pre che la ricerca sia ridondante/inutile

**Comment by Federico81** [comment]
sono d'accordo
è che non mi viene in mente molto altro di sensato su cui filtrare

**Comment by pcav** [comment]
allora chiudiamo, ok?

**Comment by Federico81** [comment]
ok
