### ISSUE TITLE
Mostrare affiliazioni corsari

### ISSUE THREAD

**Issue by pcav** [pcav/pirati#3]
che ne dici di dare colori diversi per i vari ´per´?

bello!
oppure (ma non so se si può) mettere di fianco la bandiera dell'epoca

**Comment by Federico81** [comment]
le bandierine dici che diventano un pasticcio vero? considera che sarebbero gif credo e che servirebbe una dimensione minima in px per dargli un senso, quindi forse si

**Comment by pcav** [comment]
credo che verrebbero molto appiccicate. eventualmente potremmo applicarle solo a livelli di zoom più elevati.

**Comment by Federico81** [comment]
sono d'accordo con te, rischia di diventare tutto poco leggibile

**Comment by pcav** [comment]
lascio a te la decisione se chiudere il ticket
grazie

**Comment by Federico81** [comment]
chiuso

Il giorno ven 17 nov 2023 alle ore 10:51 Paolo Cavallini <
***@***.***> ha scritto:
