### ISSUE TITLE
Modificare stile

### ISSUE THREAD

**Issue by pcav** [pcav/pirati#4]
inviiare css da modificare per popup etc

**Comment by pcav** [comment]
Direi che la cosa migliore è fare un utente e modificare direttamente il CSS così:
https://docs.lizmap.com/current/it/publish/customization/themes.html#additional-css
OK?

**Comment by Federico81** [comment]
ok

Il giorno gio 26 ott 2023 alle ore 09:31 Paolo Cavallini <
***@***.***> ha scritto:

**Comment by pcav** [comment]
Utente creato, per cortesia verifica se puoi modificare lo stile.

**Comment by Federico81** [comment]
allora, il problema è che se modifico lo stile.css resta a una priorità inferiore rispetto alla marcatura in linea. Infatti nell'html c'è un tag <div id="liz_layer_popup" class="olPopup lizmapPopup" ...> che ha uno style in linea e quello dà un'istruzione css più prossima (che comanda sempre e non si può sovrascrivere). 
Bisogna rintracciare quella riga e dove c'è scritto left:628px sostituire con left:30vw e dove c'è scritto width:500px sostituire con width:40vw. L'ho testato nel tool di anteprima e funziona

**Comment by pcav** [comment]
Ti allego qua lo stile di default, che puoi modificare a piacimento, poi lo installo io sul progetto.
Grazie.
[lizmapWebClient_default_theme.zip](https://github.com/pcav/pirati/files/13373402/lizmapWebClient_default_theme.zip)

**Comment by Federico81** [comment]
Ciao Paolo, come ti dicevo sopra anche se modifico il css non modificherei lo stile della pagina.
Questo perché il foglio di stile a cascata ha come caratteristica proprio quella di essere a cascata: le istruzioni si ereditano come in un albero, se c'è un'istruzione più prossima viene cancellata l'istruzione precedente.
Nel nostro caso se scrivo nel css la riga
#liz_layer_popup {left:30vw; width:500px} incontrerà un'istruzione più prossima che è marcata dentro l'html e la cancella questo perché nel tag <div id="liz_layer_popup" class="olPopup lizmapPopup"... c'è un attributo style che ri-assegna quei valori e li sovrascrive. Quindi sarebbe da modificare nell'html quell'istruzione, comunque sia ho fatto una prova, ho modificato il file map.css usando !important te lo mando via posta

**Comment by pcav** [comment]
dovrei aver applicato il tuo css. per cortesia verifica.
grazie.

**Comment by Federico81** [comment]
si e funziona ;)
chiudo
